const os = require('os');
console.log(os);
console.log(os.cpus());
console.log(os.freemem());
console.log(os.getPriority());
console.log(os.homedir());
console.log(os.hostname());
console.log(os.loadavg());
console.log(os.networkInterfaces());
console.log(os.type());
console.log(os.userInfo());
console.log(os.uptime());
console.log(os.version());